import { getEquipmentStats as engineGetEquipmentStats } from '../../../js/engine/shared/inventory/EquipmentService.js';

/**
 * Generates the localized display name for a piece of equipment.
 * @param {Object} item The equipment data object.
 * @param {Function} t Translation function.
 * @returns {String} Localized name (e.g. "Wooden Dagger +1").
 */
export function getEquipmentName(item, t) {
    if (!item) return t('inventory_uxelm_empty_slot');

    const tierName = t('inventory_info_tier_' + item.material);

    if (item.type === 'weapon') {
        const familyName = t('inventory_info_family_' + item.family);
        return `${tierName} ${familyName} +${item.level || 0}`;
    } else {
        const archName = t('inventory_info_archetype_' + item.archetype);
        const slotName = t('inventory_info_slot_' + item.slot);
        return `${tierName} ${archName} ${slotName} +${item.level || 0}`;
    }
}

/**
 * Calculates primary stats generated by a piece of equipment.
 * @param {Object} item The equipment data object.
 * @returns {Object} Calculated stats bonuses.
 */
export function getEquipmentStats(item) {
    return engineGetEquipmentStats(item);
}

/**
 * Formats a stat list into a localized display string.
 * @param {Object} item The equipment data object.
 * @param {Function} t Translation function.
 * @returns {String} Localized stat string (e.g. "+5 Defense, +10 HP").
 */
export function getFormattedStats(item, t) {
    const statsObj = getEquipmentStats(item);
    const statLines = [];
    
    if (statsObj.strength) {
        statLines.push(`+${statsObj.strength} ${t('heroes_info_stat_strength')}`);
    }
    if (statsObj.defense) {
        statLines.push(`+${statsObj.defense} ${t('heroes_info_stat_defense')}`);
    }
    if (statsObj.maxHp) {
        statLines.push(`+${statsObj.maxHp} ${t('heroes_info_stat_hp')}`);
    }
    if (statsObj.maxMp) {
        statLines.push(`+${statsObj.maxMp} ${t('heroes_info_stat_mp')}`);
    }
    if (statsObj.magicPower) {
        statLines.push(`+${statsObj.magicPower} ${t('heroes_info_stat_magic_power')}`);
    }
    if (statsObj.speed) {
        const sign = statsObj.speed > 0 ? '+' : '';
        statLines.push(`${sign}${statsObj.speed} ${t('heroes_info_stat_speed')}`);
    }
    if (statsObj.evasion) {
        const sign = statsObj.evasion > 0 ? '+' : '';
        statLines.push(`${sign}${statsObj.evasion}% ${t('heroes_info_stat_evasion')}`);
    }
    if (statsObj.mpCostReduction) {
        statLines.push(`-${statsObj.mpCostReduction}% ${t('heroes_info_stat_mpCostReduction')}`);
    }
    
    return statLines.join(', ') || t('inventory_info_no_stats');
}
